- name: Configuration deployment with EAPI
  hosts: D1
  gather_facts: false
  
  tasks:
    - name: etcport cfg 배포
      eos_config:
        src: "./inventory/config/{{ inventory_hostname }}.cfg"
        replace: line
        save_when: modified
        backup: "{{ eos_config_deploy_eapi_pre_running_config_backup }}"
        backup_options:
          filename: "etcport_{{ pre_running_config_backup_filename }}"
          dir_path: "{{ pre_running_config_backup_dir }}"